#配置数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dcy?useSSL=false
    username: root
    password: 159357
    driver-class-name: com.mysql.jdbc.Driver

server:
#  servlet:
#    context-path: /aaa #  配置路径
  port: 8080  #服务端口

#测试
#temp:
#  id: 1
#  name: "dcy"
#  content: "${cupsize}"
#
#cupsize: "cupsize is F"